root: true
extends:
  - "prettier"
rules:
  "no-unexpected-multiline": "warn"
  "react/display-name": "off"
  "semi": 0
  "react/no-unescaped-entities": 0
plugins:
  - "@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - "./tsconfig.json"
    - "./.eslintrc.js"
